theme: jekyll-theme-slate
title: Ian Edmiston NC REALTOR®/Broker
subtitle: NC REALTOR®/Broker
background: URL(![FullSizeRender](https://user-images.githubusercontent.com/66488116/83917179-6e65c700-a744-11ea-9870-4fb3b4e39ce4.jpg))
